import type { PsychologicalAssessmentStepConfig } from './psychologicalAssessment.types';

export const PSYCHOLOGICAL_ASSESSMENT_TOTAL_QUESTIONS = 16;

export const psychologicalAssessmentSteps: PsychologicalAssessmentStepConfig[] = [
  {
    key: 'pre_training_emotional_awareness',
    category: 'AUTOPERCEPÇÃO',
    question: 'Você costuma entender como está se sentindo antes do treino?',
    subtitle: 'Consciência emocional pré-treino.',
    inputType: 'slider',
    min: 0,
    max: 10,
    minLabel: 'Nunca',
    maxLabel: 'Sempre',
  },
  {
    key: 'emotional_trigger_recognition',
    category: 'AUTOPERCEPÇÃO',
    question: 'Você consegue identificar quando algo está te afetando emocionalmente?',
    subtitle: 'Reconhecimento de gatilhos.',
    inputType: 'slider',
    min: 0,
    max: 10,
    minLabel: 'Nunca',
    maxLabel: 'Sempre',
  },
  {
    key: 'weekly_mood_awareness',
    category: 'AUTOPERCEPÇÃO',
    question: 'Você percebe mudanças no seu humor ao longo da semana?',
    subtitle: 'Awareness emocional.',
    inputType: 'slider',
    min: 0,
    max: 10,
    minLabel: 'Nunca',
    maxLabel: 'Sempre',
  },
  {
    key: 'bad_training_mental_physical_split',
    category: 'AUTOPERCEPÇÃO',
    question:
      'Quando você tem um treino ruim, consegue separar o que foi mental do que foi técnico/físico?',
    subtitle: 'Escreva com suas palavras.',
    inputType: 'text',
    textPlaceholder: 'Digite aqui...',
  },
  {
    key: 'post_training_emotional_reflection',
    category: 'AUTOPERCEPÇÃO',
    question:
      'Depois do treino, você dedica algum momento pra refletir sobre como se sentiu emocionalmente?',
    subtitle: 'Não só fisicamente.',
    inputType: 'text',
    textPlaceholder: 'Digite aqui...',
  },
  {
    key: 'training_focus_level',
    category: 'FOCO E PERFORMANCE',
    question: 'Você sente que consegue se concentrar bem nos treinos?',
    subtitle: 'Nível de foco durante atividade.',
    inputType: 'slider',
    min: 0,
    max: 10,
    minLabel: 'Nunca',
    maxLabel: 'Sempre',
  },
  {
    key: 'error_recovery_speed',
    category: 'FOCO E PERFORMANCE',
    question: 'Quando você comete um erro, consegue se recuperar rápido?',
    subtitle: 'Resiliência mental.',
    inputType: 'slider',
    min: 0,
    max: 10,
    minLabel: 'Nunca',
    maxLabel: 'Sempre',
  },
  {
    key: 'mental_interference',
    category: 'FOCO E PERFORMANCE',
    question: 'Sua mente costuma atrapalhar seu desempenho?',
    subtitle: 'Interferência mental.',
    inputType: 'slider',
    min: 0,
    max: 10,
    minLabel: 'Nunca',
    maxLabel: 'Sempre',
  },
  {
    key: 'anxiety_coping_strategies',
    category: 'REGULAÇÃO EMOCIONAL',
    question: 'Você sabe o que fazer quando está ansioso ou nervoso?',
    subtitle: 'Estratégias de coping.',
    inputType: 'slider',
    min: 0,
    max: 10,
    minLabel: 'Nunca',
    maxLabel: 'Sempre',
  },
  {
    key: 'emotions_training_impact',
    category: 'REGULAÇÃO EMOCIONAL',
    question: 'Você sente que suas emoções atrapalham seu treino?',
    subtitle: 'Impacto emocional.',
    inputType: 'slider',
    min: 0,
    max: 10,
    minLabel: 'Nunca',
    maxLabel: 'Sempre',
  },
  {
    key: 'difficult_times_help_seeking',
    category: 'REGULAÇÃO EMOCIONAL',
    question:
      'Quando você está passando por algo difícil, você procura ajuda ou guarda pra si?',
    subtitle: 'Escreva com suas palavras.',
    inputType: 'text',
    textPlaceholder: 'Digite aqui...',
  },
  {
    key: 'team_belonging',
    category: 'RELAÇÃO COM O TIME',
    question: 'Você se sente bem dentro do grupo/time?',
    subtitle: 'Pertencimento.',
    inputType: 'slider',
    min: 0,
    max: 10,
    minLabel: 'Nada',
    maxLabel: 'Completamente',
  },
  {
    key: 'colleague_comfort',
    category: 'RELAÇÃO COM O TIME',
    question: 'Você se sente à vontade com seus colegas?',
    subtitle: 'Conforto social.',
    inputType: 'slider',
    min: 0,
    max: 10,
    minLabel: 'Nada',
    maxLabel: 'Completamente',
  },
  {
    key: 'training_intentionality',
    category: 'CONEXÃO COM O TREINO',
    question: 'Você entra no treino com clareza do que quer melhorar?',
    subtitle: 'Intencionalidade.',
    inputType: 'slider',
    min: 0,
    max: 10,
    minLabel: 'Nunca',
    maxLabel: 'Sempre',
  },
  {
    key: 'athlete_progress_perception',
    category: 'CONEXÃO COM O TREINO',
    question: 'Você sente que está evoluindo como atleta?',
    subtitle: 'Percepção de progresso.',
    inputType: 'slider',
    min: 0,
    max: 10,
    minLabel: 'Nada',
    maxLabel: 'Muito',
  },
  {
    key: 'emotional_patterns_as_athlete',
    category: 'CONEXÃO COM O TREINO',
    question:
      'Quais são seus maiores padrões emocionais como atleta — o que te fortalece e o que te sabota?',
    subtitle: 'Escreva com suas palavras.',
    inputType: 'text',
    textPlaceholder: 'Digite aqui...',
  },
];
