import { StyleSheet, Platform } from 'react-native';
import { frauncesFont, instrumentSansFont } from '@/constants/onboardingTheme';

const systemSans = Platform.OS === 'ios' ? 'System' : 'sans-serif';

export const authStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  root: {
    flex: 1,
    backgroundColor: '#1D1916',
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1D1916',
  },
  backgroundImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    opacity: 0.7,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 28,
  },
  content: {
    width: '100%',
    justifyContent: 'space-between',
  },
  header: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '100%',
    paddingTop: 48,
  },
  mainSection: {
    width: '100%',
    paddingTop: 8,
    paddingBottom: 20,
  },
  footerSection: {
    width: '100%',
    paddingBottom: 8,
  },
  budWordmark: {
    fontSize: 96,
    fontWeight: '400',
    fontFamily: frauncesFont,
    color: '#FFFFFF',
    lineHeight: 110,
    textAlign: 'center',
    marginBottom: 4,
    ...(Platform.OS === 'android' ? { includeFontPadding: false } : {}),
  },
  title: {
    fontSize: 64,
    fontWeight: '400',
    fontFamily: frauncesFont,
    color: '#FFFFFF',
    marginBottom: 12,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 24,
    fontWeight: '400',
    fontFamily: instrumentSansFont,
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: 30,
    marginTop: 4,
  },
  socialSection: {
    gap: 12,
  },
  socialButton: {
    height: 54,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 15,
  },
  socialButtonPrimary: {
    marginBottom: 0,
  },
  socialButtonPrimaryFirst: {
    marginTop: 0,
  },
  socialButtonApple: {
    backgroundColor: '#000000',
  },
  socialButtonGoogle: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.17,
    shadowRadius: 1.5,
    elevation: 3,
  },
  socialButtonText: {
    fontSize: 20,
    fontWeight: '500',
    fontFamily: systemSans,
  },
  socialButtonTextApple: {
    color: '#FFFFFF',
  },
  socialButtonTextGoogle: {
    color: 'rgba(0, 0, 0, 0.54)',
  },
  socialIconContainer: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emailSection: {
    width: '100%',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 4,
    marginBottom: 16,
    paddingVertical: 4,
  },
  backButtonText: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: instrumentSansFont,
    color: '#FFFFFF',
  },
  emailAuthToggle: {
    height: 54,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
  },
  emailAuthToggleText: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: instrumentSansFont,
    color: '#FFFFFF',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 12,
    padding: 4,
    marginBottom: 24,
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 10,
  },
  tabActive: {
    backgroundColor: '#FFFFFF',
  },
  tabText: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: instrumentSansFont,
    color: 'rgba(255, 255, 255, 0.7)',
  },
  tabTextActive: {
    color: '#1D1916',
  },
  form: {
    gap: 16,
    marginBottom: 24,
  },
  inputGroup: {
    gap: 8,
  },
  labelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  label: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: instrumentSansFont,
    color: '#FFFFFF',
  },
  forgotPassword: {
    fontSize: 14,
    fontFamily: instrumentSansFont,
    color: '#FFFFFF',
    textDecorationLine: 'underline',
  },
  input: {
    height: 52,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    fontFamily: instrumentSansFont,
    color: '#000000',
    borderWidth: 1,
    borderColor: '#E5E5E5',
  },
  passwordInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 52,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E5E5',
  },
  passwordInput: {
    flex: 1,
    height: 52,
    paddingHorizontal: 16,
    fontSize: 16,
    fontFamily: instrumentSansFont,
    color: '#000000',
  },
  eyeIcon: {
    paddingRight: 16,
    paddingLeft: 8,
  },
  button: {
    height: 54,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: instrumentSansFont,
    color: '#1D1916',
  },
  signupHint: {
    fontSize: 13,
    fontFamily: instrumentSansFont,
    color: 'rgba(255, 255, 255, 0.75)',
    lineHeight: 18,
    textAlign: 'center',
    marginTop: 16,
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 16,
    gap: 12,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.35)',
  },
  dividerText: {
    fontSize: 14,
    fontFamily: instrumentSansFont,
    color: 'rgba(255, 255, 255, 0.7)',
  },
  bottomSection: {
    gap: 20,
    paddingBottom: 20,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  termsText: {
    fontSize: 16,
    fontWeight: '400',
    fontFamily: instrumentSansFont,
    color: '#FFFFFF',
    textAlign: 'center',
    paddingHorizontal: 8,
    lineHeight: 22,
  },
  termsLink: {
    textDecorationLine: 'underline',
    color: '#FFFFFF',
  },
  forgotPasswordTitle: {
    fontSize: 32,
    fontWeight: '400',
    fontFamily: frauncesFont,
    color: '#FFFFFF',
    textAlign: 'left',
    marginBottom: 12,
    lineHeight: 38,
    ...(Platform.OS === 'android' ? { includeFontPadding: false } : {}),
  },
  forgotPasswordDescription: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: instrumentSansFont,
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'left',
    lineHeight: 20,
    marginBottom: 24,
  },
  textLinkButton: {
    alignItems: 'center',
    paddingVertical: 12,
    marginTop: 8,
  },
  textLinkButtonText: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: instrumentSansFont,
    color: '#FFFFFF',
  },
  emailHighlight: {
    fontWeight: '600',
    color: '#FFFFFF',
  },
  forgotPasswordContent: {
    width: '100%',
    justifyContent: 'flex-start',
  },
  forgotPasswordNavBar: {
    width: '100%',
    paddingHorizontal: 24,
    paddingBottom: 8,
  },
  forgotPasswordBody: {
    width: '100%',
    paddingTop: 24,
  },
});
