import { StyleSheet, Platform } from 'react-native';

export const authStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1E1E1E',
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
  },
  content: {
    width: '100%',
    justifyContent: 'space-between',
  },
  header: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '100%',
  },
  mainSection: {
    width: '100%',
    paddingVertical: 24,
  },
  footerSection: {
    width: '100%',
  },
  budWordmark: {
    fontSize: 44,
    fontWeight: '400',
    fontFamily: 'InriaSerif-Regular',
    color: '#1E3A5F',
    lineHeight: 48,
    textAlign: 'center',
    marginBottom: 10,
    ...(Platform.OS === 'android' ? { includeFontPadding: false } : {}),
  },
  partnershipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 4,
  },
  supportedByText: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    color: 'rgba(74, 74, 74, 0.55)',
    letterSpacing: 0.6,
    lineHeight: 15,
    textAlign: 'center',
    ...(Platform.OS === 'android' ? { includeFontPadding: false } : {}),
  },
  elevenLabsBadge: {
    width: 200,
    height: 36,
  },
  title: {
    fontSize: 64,
    fontWeight: '400',
    fontFamily: 'InriaSerif-Regular',
    color: '#1E3A5F',
    marginBottom: 12,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    color: 'rgba(74, 74, 74, 0.75)',
    textAlign: 'center',
    lineHeight: 18,
    marginTop: 10,
  },
  socialSection: {
    gap: 12,
  },
  socialButton: {
    height: 52,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  socialButtonPrimary: {
    marginBottom: 0,
  },
  socialButtonPrimaryFirst: {
    marginTop: 0,
  },
  socialButtonApple: {
    backgroundColor: '#000000',
  },
  socialButtonGoogle: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E5E5',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  socialButtonText: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  socialButtonTextApple: {
    color: '#FFFFFF',
  },
  socialButtonTextGoogle: {
    color: '#000000',
  },
  socialIconContainer: {
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emailSection: {
    width: '100%',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 4,
    marginBottom: 16,
    paddingVertical: 4,
  },
  backButtonText: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    color: '#1E3A5F',
  },
  emailAuthToggle: {
    height: 52,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderWidth: 1,
    borderColor: 'rgba(30, 58, 95, 0.2)',
  },
  emailAuthToggleText: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    color: '#1E3A5F',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 12,
    padding: 4,
    marginBottom: 24,
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 10,
  },
  tabActive: {
    backgroundColor: '#FFFFFF',
  },
  tabText: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    color: '#666666',
  },
  tabTextActive: {
    color: '#1E3A5F',
  },
  form: {
    gap: 16,
    marginBottom: 24,
  },
  inputGroup: {
    gap: 8,
  },
  labelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  label: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    color: '#4A4A4A',
  },
  forgotPassword: {
    fontSize: 14,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    color: '#1E3A5F',
  },
  input: {
    height: 52,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    color: '#000000',
    borderWidth: 1,
    borderColor: '#E5E5E5',
  },
  passwordInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 52,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E5E5',
  },
  passwordInput: {
    flex: 1,
    height: 52,
    paddingHorizontal: 16,
    fontSize: 16,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    color: '#000000',
  },
  eyeIcon: {
    paddingRight: 16,
    paddingLeft: 8,
  },
  button: {
    height: 52,
    backgroundColor: '#1E3A5F',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    color: '#FFFFFF',
  },
  signupHint: {
    fontSize: 13,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    color: 'rgba(74, 74, 74, 0.75)',
    lineHeight: 18,
    textAlign: 'center',
    marginTop: 16,
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 16,
    gap: 12,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(74, 74, 74, 0.3)',
  },
  dividerText: {
    fontSize: 14,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    color: '#666666',
  },
  bottomSection: {
    gap: 20,
    paddingBottom: 20,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  googleIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  googleIconText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4285F4',
  },
  termsText: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    color: '#666666',
    textAlign: 'center',
    paddingHorizontal: 12,
    lineHeight: 20,
    marginTop: 12,
  },
  disclaimerText: {
    fontSize: 12,
    fontWeight: '400',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    color: '#666666',
    textAlign: 'center',
    paddingHorizontal: 12,
    lineHeight: 17,
  },
  termsLink: {
    textDecorationLine: 'underline',
    color: '#666666',
  },
  forgotPasswordTitle: {
    fontSize: 32,
    fontWeight: '400',
    fontFamily: 'InriaSerif-Regular',
    color: '#1E3A5F',
    textAlign: 'left',
    marginBottom: 12,
    lineHeight: 38,
    ...(Platform.OS === 'android' ? { includeFontPadding: false } : {}),
  },
  forgotPasswordDescription: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    color: 'rgba(74, 74, 74, 0.75)',
    textAlign: 'left',
    lineHeight: 20,
    marginBottom: 24,
  },
  textLinkButton: {
    alignItems: 'center',
    paddingVertical: 12,
    marginTop: 8,
  },
  textLinkButtonText: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    color: '#1E3A5F',
  },
  emailHighlight: {
    fontWeight: '600',
    color: '#1E3A5F',
  },
  forgotPasswordContent: {
    width: '100%',
    justifyContent: 'flex-start',
  },
  forgotPasswordNavBar: {
    width: '100%',
    paddingHorizontal: 24,
    paddingBottom: 8,
  },
  forgotPasswordBody: {
    width: '100%',
    paddingTop: 24,
  },
});

