import { StyleSheet } from 'react-native';

import { frauncesFont } from '@/constants/onboardingTheme';

export const deepInsightSheetStyles = StyleSheet.create({
  modalRoot: {
    flex: 1,
    backgroundColor: '#4A6572',
  },
  stateContainer: {
    flex: 1,
    backgroundColor: '#4A6572',
  },
  contentRoot: {
    flex: 1,
    backgroundColor: '#4A6572',
  },
  headerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    paddingHorizontal: 16,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  loadingText: {
    fontFamily: frauncesFont,
    fontSize: 22,
    fontStyle: 'italic',
    color: '#ffffff',
    textAlign: 'center',
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
  },
  centerContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
    paddingBottom: 32,
  },
  centerTitle: {
    fontFamily: frauncesFont,
    fontSize: 20,
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 28,
  },
  centerSubtitle: {
    fontFamily: frauncesFont,
    fontSize: 15,
    color: 'rgba(255, 255, 255, 0.6)',
    textAlign: 'center',
    marginBottom: 32,
  },
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 32,
  },
  progressLabel: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.4)',
  },
  progressTrack: {
    width: 128,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    borderRadius: 3,
  },
  outlineButton: {
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  outlineButtonText: {
    fontFamily: frauncesFont,
    fontSize: 16,
    color: '#ffffff',
  },
  scroll: {
    flex: 1,
  },
  hero: {
    minHeight: 240,
    justifyContent: 'flex-end',
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
  },
  heroTitleBlock: {
    paddingHorizontal: 24,
    paddingBottom: 28,
  },
  heroSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: 'rgba(255, 255, 255, 0.7)',
    marginBottom: 12,
  },
  heroHeadline: {
    fontFamily: frauncesFont,
    fontSize: 24,
    color: '#ffffff',
    lineHeight: 32,
  },
  body: {
    backgroundColor: '#4A6572',
    paddingTop: 8,
  },
  introCard: {
    marginHorizontal: 16,
    marginBottom: 24,
    padding: 20,
    borderRadius: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  introText: {
    fontFamily: frauncesFont,
    fontSize: 15,
    color: 'rgba(255, 255, 255, 0.85)',
    lineHeight: 24,
  },
  introSignature: {
    fontFamily: frauncesFont,
    fontSize: 13,
    fontStyle: 'italic',
    color: 'rgba(255, 255, 255, 0.6)',
    textAlign: 'center',
    marginTop: 16,
  },
  section: {
    paddingHorizontal: 24,
    marginBottom: 32,
  },
  sectionTitle: {
    fontFamily: frauncesFont,
    fontSize: 20,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 16,
    lineHeight: 28,
  },
  sectionBody: {
    fontFamily: frauncesFont,
    fontSize: 15,
    color: 'rgba(255, 255, 255, 0.75)',
    lineHeight: 24,
  },
  takeawayCard: {
    marginHorizontal: 24,
    marginBottom: 32,
    borderRadius: 16,
    overflow: 'hidden',
    minHeight: 120,
  },
  takeawayOverlay: {
    padding: 24,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
  },
  takeawayLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 2,
    color: 'rgba(255, 255, 255, 0.6)',
    marginBottom: 12,
    textTransform: 'uppercase',
  },
  takeawayText: {
    fontFamily: frauncesFont,
    fontSize: 15,
    color: '#ffffff',
    lineHeight: 24,
  },
  ctaSection: {
    paddingHorizontal: 24,
    paddingBottom: 8,
  },
  ctaButton: {
    marginTop: 24,
    height: 56,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaButtonText: {
    fontFamily: frauncesFont,
    fontSize: 16,
    color: '#ffffff',
  },
  feedbackSection: {
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
  },
  feedbackLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.4)',
    textAlign: 'center',
    letterSpacing: 2,
    marginBottom: 24,
    textTransform: 'uppercase',
  },
  feedbackRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 32,
  },
  feedbackButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  feedbackButtonActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  feedbackThanks: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.4)',
    textAlign: 'center',
    marginTop: 16,
  },
});
