export const CLICK_EVENTS = {
  TAB_SELECT: 'tab_select',
  TAB_CHAT: 'tab_select',
  TAB_EXPLORE: 'tab_select',
  TAB_ACTIVITIES: 'tab_select',
  TAB_HISTORY: 'tab_select',
  ACTIVITIES_HOME_CHECKIN: 'checkin_open_from_home',
  EXPLORE_INSIGHT_MESSAGE: 'explore_insight_message_tap',
  EXPLORE_INSIGHT_VOICE: 'explore_insight_voice_tap',
  HISTORY_CONVERSATION_OPEN: 'history_conversation_open',
  HISTORY_DEEP_INSIGHT_OPEN: 'history_insight_open',
  SETTINGS_PSYCHOLOGICAL_ASSESSMENT: 'settings_assessment_open',
  CHECKIN_INTRO_START: 'checkin_intro_start',
  CHECKIN_ACTIVITIES_SELECT: 'checkin_type_select',
  PSYCHOLOGICAL_ASSESSMENT_START: 'assessment_start',
} as const;

export const ACTION_EVENTS = {
  MESSAGE_SENT: 'chat_message_send',
  VOICE_SESSION_STARTED: 'voice_session_start',
  VOICE_SESSION_ENDED: 'voice_session_end',
  CHECKIN_STARTED: 'checkin_start',
  CHECKIN_COMPLETED: 'checkin_complete',
  CHECKIN_ABANDONED: 'checkin_abandon',
  CHECKIN_INTRO_ABANDONED: 'checkin_intro_abandon',
  CHECKIN_REPORT_VIEWED: 'checkin_report_view',
  PSYCHOLOGICAL_ASSESSMENT_COMPLETED: 'assessment_complete',
  PSYCHOLOGICAL_ASSESSMENT_ABANDONED: 'assessment_abandon',
  ONBOARDING_COMPLETED: 'onboarding_complete',
  ONBOARDING_ABANDONED: 'onboarding_abandon',
  EXPLORE_INSIGHT_VIEWED: 'explore_insight_view',
  EXPLORE_INSIGHT_BLOCKED: 'explore_insight_blocked',
  SIGN_OUT: 'auth_sign_out',
} as const;
