import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "../supabase/functions/_shared/clinical-chunks");
const out = path.resolve(__dirname, "../supabase/functions/_shared/clinicalChunkContents.ts");

const sources = [
  ["R1_tecnicas/TCC_beck_ellis.md", "tccBeckEllis"],
  ["R1_tecnicas/ACT_hayes.md", "actHayes"],
  ["R1_tecnicas/DBT_linehan.md", "dbtLinehanTechnique"],
  ["R1_tecnicas/CFT_gilbert.md", "cftGilbertTechnique"],
  ["R1_tecnicas/narrativa_white_epston.md", "narrativaWhiteEpston"],
  ["R1_tecnicas/mindfulness_mbsr_mbct.md", "mindfulnessMbsr"],
  ["R1_tecnicas/esquemas_young.md", "esquemasYoung"],
  ["R1_tecnicas/IFS_schwartz.md", "ifsSchwartz"],
  ["R1_tecnicas/EMDR_shapiro.md", "emdrShapiro"],
  ["R2_transcricoes/TCC_beck_abe_sessao2.txt", "tccBeckAbe"],
  ["R2_transcricoes/pessoa_centrada_rogers_gloria_1965.txt", "rogersGloria"],
  ["R2_transcricoes/TCC_camh_simulacao_gambling.txt", "tccCamhGambling"],
  ["R2_transcricoes/DBT_linehan_sessao_real.txt", "dbtLinehanTranscript"],
  ["R2_transcricoes/narrativa_white_workshop_1990.txt", "narrativaWhiteWorkshop"],
  ["R2_transcricoes/CFT_gilbert_entrevista.txt", "cftGilbertTranscript"],
  ["R3_artigos/referencias_cientificas.md", "referenciasCientificas"],
  ["R4_psicanalise/psicanalise_expandida.md", "psicanaliseExpandida"],
  ["R5_psicoeducacao/temas.md", "psicoeducacaoTemas"],
  ["R6_glossario/glossario_clinico.md", "glossarioClinico"],
  ["R8_sessoes_modelo/01_resistencia_silencio.md", "r8ResistenciaSilencio"],
  ["R8_sessoes_modelo/02_pedido_solucao.md", "r8PedidoSolucao"],
  ["R8_sessoes_modelo/03_contradicao_defesa.md", "r8ContradicaoDefesa"],
  ["R8_sessoes_modelo/04_to_bem_com_algo.md", "r8ToBemComAlgo"],
  ["R8_sessoes_modelo/05_performance_pilar.md", "r8PerformancePilar"],
  ["R8_sessoes_modelo/06_questiona_processo.md", "r8QuestionaProcesso"],
  ["R8_sessoes_modelo/07_crise_leve.md", "r8CriseLeve"],
  ["R8_sessoes_modelo/08_corner_cases.md", "r8CornerCases"],
  ["R8_sessoes_modelo/09_arco_3dias_performance.md", "r8Arco3diasPerformance"],
  ["R8_sessoes_modelo/10_arco_3dias_conflito_pai.md", "r8Arco3diasConflitoPai"],
  ["R8_sessoes_modelo/11_arco_4dias_burnout.md", "r8Arco4diasBurnout"],
  ["R8_sessoes_modelo/12_sessoes_curtas_variadas.md", "r8SessoesCurtasVariadas"],
];

const lines = ["// Auto-generated by scripts/generateClinicalChunkContents.mjs", ""];
const entries = [];

for (const [relativePath, varName] of sources) {
  const content = fs.readFileSync(path.join(root, relativePath), "utf8");
  lines.push(`const ${varName} = ${JSON.stringify(content)};`);
  entries.push(`  ${JSON.stringify(relativePath)}: ${varName},`);
}

lines.push("", "export const CLINICAL_CHUNK_CONTENT: Record<string, string> = {");
lines.push(...entries);
lines.push("};", "");

fs.writeFileSync(out, lines.join("\n"));
console.log(`Generated ${out} (${fs.statSync(out).size} bytes)`);
