import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "../supabase/functions/_shared/clinical-chunks");
const out = path.resolve(__dirname, "../supabase/functions/_shared/clinicalChunkContents.ts");

const sources = [
  ["R1_tecnicas/TCC_beck_ellis.md", "tccBeckEllis"],
  ["R1_tecnicas/ACT_hayes.md", "actHayes"],
  ["R1_tecnicas/DBT_linehan.md", "dbtLinehanTechnique"],
  ["R1_tecnicas/CFT_gilbert.md", "cftGilbertTechnique"],
  ["R1_tecnicas/narrativa_white_epston.md", "narrativaWhiteEpston"],
  ["R1_tecnicas/mindfulness_mbsr_mbct.md", "mindfulnessMbsr"],
  ["R1_tecnicas/esquemas_young.md", "esquemasYoung"],
  ["R1_tecnicas/IFS_schwartz.md", "ifsSchwartz"],
  ["R1_tecnicas/EMDR_shapiro.md", "emdrShapiro"],
  ["R2_transcricoes/TCC_beck_abe_sessao2.txt", "tccBeckAbe"],
  ["R2_transcricoes/pessoa_centrada_rogers_gloria_1965.txt", "rogersGloria"],
  ["R2_transcricoes/TCC_camh_simulacao_gambling.txt", "tccCamhGambling"],
  ["R2_transcricoes/DBT_linehan_sessao_real.txt", "dbtLinehanTranscript"],
  ["R2_transcricoes/narrativa_white_workshop_1990.txt", "narrativaWhiteWorkshop"],
  ["R2_transcricoes/CFT_gilbert_entrevista.txt", "cftGilbertTranscript"],
  ["R3_artigos/referencias_cientificas.md", "referenciasCientificas"],
  ["R4_psicanalise/psicanalise_expandida.md", "psicanaliseExpandida"],
  ["R5_psicoeducacao/temas.md", "psicoeducacaoTemas"],
  ["R6_glossario/glossario_clinico.md", "glossarioClinico"],
];

const lines = ["// Auto-generated by scripts/generateClinicalChunkContents.mjs", ""];
const entries = [];

for (const [relativePath, varName] of sources) {
  const content = fs.readFileSync(path.join(root, relativePath), "utf8");
  lines.push(`const ${varName} = ${JSON.stringify(content)};`);
  entries.push(`  ${JSON.stringify(relativePath)}: ${varName},`);
}

lines.push("", "export const CLINICAL_CHUNK_CONTENT: Record<string, string> = {");
lines.push(...entries);
lines.push("};", "");

fs.writeFileSync(out, lines.join("\n"));
console.log(`Generated ${out} (${fs.statSync(out).size} bytes)`);
